### ISSUE TITLE
cx__objectScope fails when called during an update

### ISSUE THREAD

**Issue by jleeothon** [cortexlang/sqlite#16]
Given

```
sqlite::server myserver{}
int64 b: 90
b := 999
```

The script fails when I call cx_nameof(source) in an update. The update is:

```
/* ::cortex::sqlite::server::onUpdate() */
cx_void sqlite_server_onUpdate(sqlite_server _this, cx_object *observable, cx_object *source) {
/* $begin(::cortex::sqlite::server::onUpdate) */
    CX_UNUSED(_this);
    CX_UNUSED(observable);
    printf("This is an update of %s!\n", cx_nameof(source));
/* $end */
}
```

[1] <main> (testserver.cx:5)

  ...
  165086024: DEFINE_WV 0 0 164990100 0
  165086044: DEFINE_WV 0 0 164952988 0
  165086064: UPDATEBEGIN_WV 0 0 164798132 0
  165086084: SET_DPV 40628 2514 999 0

> 165086104: UPDATEEND_WV 0 0 164798132 0
>   165086124: STOP

![cortex dev box](https://cloud.githubusercontent.com/assets/6202537/6472031/109660f0-c1b5-11e4-8619-3a0571705246.png)

The address `o->attrs` is unaccessible.

**Comment by SanderMertens** [comment]
Observers don't always receive a `source` parameter. Source denotes the origin of an event. By default events don't have an origin, unless explicitly provided.

Under the following conditions, a source parameter is provided:
- When using `cx_updateFrom(cx_object observable, cx_object source)`
- When updating from a method implemented in cx, the language will automatically pass `this` as the source
- When receiving a `declare` event, the source is set to the newly created object, while the observable parameter points to the object on which the observer is attached.
