### ISSUE TITLE
Database primary keys need to be stored somewhere in the object store

### ISSUE THREAD

**Issue by jleeothon** [cortexlang/sqlite#8]
Many serialization operations need this, e.g. the WHERE clause in update statements.

Proposed solutions:
- Our database "server" has a map of object annotations.
- We use build-in object annotations (which funny, have not yet build :stuck_out_tongue_closed_eyes:).

We need to go for the first one. More information coming soon.

**Comment by jleeothon** [comment]
![office lens_20150302_141857_processed](https://cloud.githubusercontent.com/assets/6202537/6449636/d327885c-c0e7-11e4-8cae-2d4e24bbcacb.jpg)

The "server" and the serializers are different projects.
The serializer would depend on the "server" to retrieve database id's.
And the server would obviously depend on the serializer. I think that's an error in this design.

**Comment by jleeothon** [comment]
In order to solve it, we could have another object in the store that keeps track of these these ids and any other serialization data. It lies in the same build substructure as the serializer. It doesn't sound very nice, though.
Both the serializer and the ORM interact with it.
The big, ugly downside is that this would be thread-unsafe.

**Comment by SanderMertens** [comment]
I'd work around this issue for now until we have annotations (which shouldn't be too long from now).

**Comment by jleeothon** [comment]
This is sort of sorted now that both parts of the project (which are currently called "connector" and "serializer") are under the same build unit.
Also, yes, annotations are going to help solve the issue of how to get id's (regardless of whether they are database-generated or core-generated).

**Comment by jleeothon** [comment]
Right now we've been consistently using fully-scoped names for row id's. This will not be changed until annotations are provided. Closing again :stuck_out_tongue:
